"""empty message

Revision ID: 3fcad28a7b42
Revises: 274af261eff5
Create Date: 2024-04-07 20:45:53.121406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3fcad28a7b42"
down_revision: Union[str, None] = "274af261eff5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("students_progress")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students_progress",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("student_id", sa.INTEGER(), nullable=False),
        sa.Column("subject_id", sa.INTEGER(), nullable=False),
        sa.Column("current_lecture", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_lecture"],
            ["lecture.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "subject_id"),
    )
    # ### end Alembic commands ###
