"""empty message

Revision ID: e279b3823439
Revises: ac3fb82c72a6
Create Date: 2024-04-07 15:43:24.880733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e279b3823439"
down_revision: Union[str, None] = "ac3fb82c72a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lecture_test",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lecture_id", sa.Integer(), nullable=False),
        sa.Column("result_to_pass", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lecture_id"],
            ["lecture.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lecture_id"),
    )
    op.create_table(
        "test_question",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("right_answer", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "scalar",
                "moder",
                "moderfile",
                "variant",
                name="campaignstatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["lecture_test.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answer_variant",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("is_right", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["test_question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_unique_constraint(None, "lecture_lab", ["lecture_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lecture_lab", type_="unique")
    op.drop_table("answer_variant")
    op.drop_table("test_question")
    op.drop_table("lecture_test")
    # ### end Alembic commands ###
